  GOOGLE_CLIENT_ID: "GOOGLE_CLIENT_ID"
  GOOGLE_CLIENT_SECRET: "GOOGLE_CLIENT_SECRET"
  GOOGLE_API_KEY: "AIzaSyC53j_a3m4SFIYpnlO6DEA74R5bGYC0MBA"

  GITHUB_CLIENT_ID: "GITHUB_CLIENT_ID"
  GITHUB_CLIENT_SECRET: "GITHUB_CLIENT_SECRET"